name       : util-macros
version    : 1.19.1
release    : 4
source     :
    - http://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.1.tar.gz : 472ad0e41d1e0abf5ecafd29460bf1b8d47e53d4b7d3abf1f66d02dc576547b8
license    : GPL-3.0
component  : xorg.base
summary    : Macros required for building X11
description: |
    The util-macros package contains the m4 macros used by all of the Xorg packages.
patterns   : /usr/share/aclocal/xorg-macros.m4
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
