name       : util-macros
version    : 1.19.2
release    : 5
source     :
    - https://www.x.org/releases/individual/util/util-macros-1.19.2.tar.gz : 9225c45c3de60faf971979a55a5536f3562baa4b6f02246c23e98ac0c09a75b7
license    : GPL-3.0
component  : xorg.base
summary    : Macros required for building X11
description: |
    The util-macros package contains the m4 macros used by all of the Xorg packages.
patterns   : /usr/share/aclocal/xorg-macros.m4
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
