name       : util-macros
version    : 1.19.3
release    : 6
source     :
    - https://www.x.org/releases/individual/util/util-macros-1.19.3.tar.gz : 624bb6c3a4613d18114a7e3849a3d70f2d7af9dc6eabeaba98060d87e3aef35b
license    : GPL-3.0
component  : xorg.base
summary    : Macros required for building X11
description: |
    The util-macros package contains the m4 macros used by all of the Xorg packages.
patterns   : /usr/share/aclocal/xorg-macros.m4
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
